name: Run remark-cli
description: Markdown processor
author: tj-actions
inputs:
  plugins:
    description: 'List of remark plugins to be installed.'
    required: true
    default: |
      remark-toc
  files:
    description: 'Input file(s)'
    required: true
    default: |
      README.md
  args:
    description: 'Argument passed to remark cli'
    required: true
    default: "--rc-path /.remarkrc.json --use toc --output"

runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: file-text
  color: white
