name: Remark Markdown processor
description: Markdown processor
author: tj-actions
inputs:
  plugins:
    description: 'List of [remarkjs plugins](https://github.com/remarkjs/remark/blob/main/doc/plugins.md).'
    required: true
    default: "remark-toc"
  files:
    description: ' List of input markdown files '
    required: true
    default: "README.md"
  rc_path:
    description: 'Remark configuration file'
    required: false
    default: "${{ github.action_path }}/.remarkrc.json"
  args:
    description: '[remark cli](https://github.com/unifiedjs/unified-args#cli) options.'
    required: true
    default: "--use toc --output"

runs:
  using: 'composite'
  steps:
    - name: Get npm cache directory
      id: remark-npm-cache-dir
      run: |
        echo "::set-output name=dir::$(npm config get cache)"
    - uses: actions/cache@v2
      id: remark-npm-cache
      with:
        path: ${{ steps.remark-npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-remark-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-remark-node-
    - run: |
        bash $GITHUB_ACTION_PATH/entrypoint.sh
      id: remark
      shell: bash
      env:
        # INPUT_<VARIABLE_NAME> is not available in Composite run steps
        # https://github.community/t/input-variable-name-is-not-available-in-composite-run-steps/127611
        INPUT_RC_PATH: ${{ inputs.rc_path }}
        INPUT_PLUGINS: ${{ inputs.plugins }}
        INPUT_FILES: ${{ inputs.files }}
        INPUT_ARGS: ${{ inputs.args }}
branding:
  icon: file-text
  color: white
