name: Remark Markdown processor
description: Markdown processor
author: tj-actions
inputs:
  plugins:
    description: 'List of [remarkjs plugins](https://github.com/remarkjs/remark/blob/main/doc/plugins.md).'
    required: true
    default: "remark-toc"
  files:
    description: ' List of input markdown files '
    required: true
    default: "README.md"
  args:
    description: '[remark cli](https://github.com/unifiedjs/unified-args#cli) options.'
    required: true
    default: "-r /.remarkrc.json --use toc --output"

runs:
  using: 'composite'
  steps:
    - run: |
        bash $GITHUB_ACTION_PATH/entrypoint.sh
      id: remark
      shell: bash
      env:
        # INPUT_<VARIABLE_NAME> is not available in Composite run steps
        # https://github.community/t/input-variable-name-is-not-available-in-composite-run-steps/127611
        INPUT_PLUGINS: ${{ inputs.plugins }}
        INPUT_FILES: ${{ inputs.files }}
        INPUT_ARGS: ${{ inputs.args }}
branding:
  icon: file-text
  color: white
